### ISSUE TITLE
32 bit applications and 64 bit plugin

### ISSUE THREAD

**Issue by ghost** [brianferguson/HotKey.dll#1]
Hey there, 
Just wanted to let you know, using the 64 bit plugin and having a 32 bit application focused, rainmeter wont react to key presses.
Anyway, good job, thanks a bunch!

**Comment by brianferguson** [comment]
It seems to work okay for me when a 32-bit application is focused. This plugin works by setting a global hook to capture any keyboard input - so it's possible that another program can also set a keyboard hook but not return correctly essentially blocking all other keyboard hooks.

Does this happen with all 32-bit applications? Or just a few? I tried it with a few and it seems to work okay. You could try running Rainmeter as a administrator and see if that helps.

-Brian
